export enum InternalTransferErrorCode {
    NOT_FOUND = 'INTERNAL_TRANSFER.NOT_FOUND',
    VALIDATION_ERROR = 'INTERNAL_TRANSFER.VALIDATION_ERROR',
    ALREADY_EXISTS = 'INTERNAL_TRANSFER.ALREADY_EXISTS',
    UNAUTHORIZED = 'INTERNAL_TRANSFER.UNAUTHORIZED',
    FORBIDDEN = 'INTERNAL_TRANSFER.FORBIDDEN',
    DATA_SERVICE_ERROR = 'INTERNAL_TRANSFER.DATA_SERVICE_ERROR',
    REQUEST_ID_REQUIRED = 'INTERNAL_TRANSFER.REQUEST_ID_REQUIRED',
    AMOUNT_REQUIRED = 'INTERNAL_TRANSFER.AMOUNT_REQUIRED',
}
