export enum HigherErrorCode {
    AUTH_FAILED = 'HIGHER.AUTH_FAILED',
    INVALID_AUTH_RESPONSE = 'HIGHER.INVALID_AUTH_RESPONSE',
    UNAUTHORIZED = 'HIGHER.UNAUTHORIZED',
    FORBIDDEN = 'HIGHER.FORBIDDEN',
    NOT_FOUND = 'HIGHER.NOT_FOUND',
    VALIDATION_ERROR = 'HIGHER.VALIDATION_ERROR',
    REQUEST_FAILED = 'HIGHER.REQUEST_FAILED',
}
